Repository ICESAT-2HackWeek/website2022, pull requests merged in 2022-03, with the labels that each got.

#30 add schedule yaml
  book/schedule.yaml
Labels: preview

#31 add question decision tree figure
  book/_toc.yml
  book/img/IS2-HW_SupportDecisionTree.png
  book/img/SupportDecisionTree.svg
  book/reference/glossary.md
  book/reference/open_source_software.md
  book/reference/questions.md
Labels: preview

#34 update team.yml with Mikala's profile info
  book/team.yaml
Labels: preview

#36 Added Hannah Besso to the team file
  book/team.yaml
Labels: preview

#35 Fix missing links and unused files
  CONTRIBUTING.md
  book/preliminary/jupyterhub_fork_clone.md
  cookiecutter.yaml
Labels: preview

#39 Update team.yaml
  book/team.yaml
Labels: preview

#38 Schedule improvements
  book/schedule.yaml
  book/team.yaml
  {{ cookiecutter.repo_directory }}/index.html
Labels: preview

#41 Fix jupyter book links to ICESat-2 hackweek's schedule and team page
  book/_toc.yml
Labels: documentation, preview

#44 Recommend using Python 3.9 instead of Python 3.7
  book/preliminary/conda.md
  book/preliminary/python.md
Labels: documentation

#46 schedule updates: titles/topics and leads
  book/schedule.yaml
Labels: preview

#52 add Ian to team
  book/team.yaml
Labels: preview

#53 change title from hybrid to virtual
  cookiecutter.yaml
Labels: preview

#58 Add earth engine sign-up instructions
  book/_toc.yml
  book/img/gee-signup.jpg
  book/preliminary/earthengine.md
  book/preliminary/index.md
Labels: documentation, preview

#47 add initial geospatial transforms
  .github/workflows/deploy.yaml
  .github/workflows/manual.yaml
  .github/workflows/netlifypreview.yaml
  .github/workflows/qaqc.yaml
  .github/workflows/repo2docker.yaml
  .github/workflows/test.yaml
  book/_config.yml
  book/_toc.yml
  book/img/EGM2008.png
  book/img/IS2_surfaces_and_datums.png
  book/tutorials/geospatial/ATL06_to_dataframe.py
  book/tutorials/geospatial/geospatial-advanced.ipynb
  book/tutorials/geospatial/geospatial-intro.ipynb
  book/tutorials/geospatial/utilities.py
Labels: preview

#70 Added day 2 data products tutorial
  book/_toc.yml
  book/tutorials/DataProducts/DataProducts.ipynb
  book/tutorials/DataProducts/images/feart-08-00156-g001_small.jpg
Labels: preview

#79 update team to include Kelsey Bisson
  book/team.yaml
Labels: preview

#81 update tutorial index, fix links, use cache
  .github/workflows/test.yaml
  book/_config.yml
  book/_toc.yml
  book/projects/project_initialization.md
  book/reference/open_source_software.md
  book/tutorials/example/tutorial-notebook.ipynb
  book/tutorials/index.md
Labels: preview

#82 Typo fixes in DataProducts
  book/tutorials/DataProducts/DataProducts.ipynb
Labels: preview

#86 bump package versions, add git installed versions
  .github/actions/buildresources/action.yaml
  .github/workflows/binder-badge.yaml
  .github/workflows/qaqc.yaml
  .github/workflows/repo2docker-PR.yaml
  .github/workflows/repo2docker.yaml
  CONTRIBUTING.md
  binder/environment.yml
  conda/README.md
  conda/conda-linux-64.lock.yml
  conda/conda-lock.yml
  conda/conda-osx-64.lock.yml
  conda/environment.yml
  conda/lock-environment.sh
Labels: preview

#74 Visualization tutorial using Earth Engine Python API, geemap and OpenAltimetry
  book/_config.yml
  book/_toc.yml
  book/tutorials/DataVisualization/.gitignore
  book/tutorials/DataVisualization/Visualization_Earth_Engine_geemap_IS2_HW_2022.ipynb
  book/tutorials/DataVisualization/Visualization_geemap_use_examples.ipynb
  book/tutorials/DataVisualization/misc/gee_codeeditor.png
  book/tutorials/DataVisualization/utils/__init__.py
  book/tutorials/DataVisualization/utils/curve_intersect.py
  book/tutorials/DataVisualization/utils/oa.py
Labels: preview

#40 Data Visualization tutorial - 2nd half static map
  book/_config.yml
  book/_toc.yml
  book/tutorials/DataVisualization/README.md
  book/tutorials/DataVisualization/Visualization_Earth_Engine_geemap_IS2_HW_2022.ipynb
  book/tutorials/DataVisualization/dataviz2d.py
  book/tutorials/index.md
Labels: preview

#83 Tutorial/oop
  book/tutorials/ObjectOriented/OOP_tutorial.ipynb
  book/tutorials/ObjectOriented/alien.ipynb
Labels: preview

#90 shift timing of project pitching
  book/schedule.yaml
Labels: preview

#87 Tutorial/data access
  book/_toc.yml
  book/img/filter-vs-subset+tools.png
  book/img/icepyx-vs-Earthdata.png
  book/tutorials/data_access/data_access_1_intro.ipynb
  book/tutorials/data_access/data_access_2_earthdata.ipynb
  book/tutorials/data_access/data_access_3_icepyx.ipynb
  book/tutorials/data_access/img/ATL06_landing_page.png
  book/tutorials/data_access/img/DAAC_map_with_ECS.jpg
  book/tutorials/data_access/img/discovery_and_access_methods.png
  book/tutorials/data_access/img/nsidc_logo.png
Labels: preview

#91 Preliminary - Update git; Add more tips and clarify password prompt.
  book/preliminary/git.md
Labels: preview

#92 Tutorial - git; Update URLs to create a fork for personal notes.
  book/tutorials/jupyter.md
Labels: preview

#93 update schedule and add links to slides
  book/schedule.yaml
Labels: preview

#96 Data access edits
  .github/actions/buildresources/action.yaml
  book/tutorials/data_access/Accessing NSIDC DAAC Data in Earthdata Cloud.pdf
  book/tutorials/data_access/NSIDC DAAC Cloud Early Access Terms of Use.pdf
  book/tutorials/data_access/data_access_1_intro.ipynb
  book/tutorials/data_access/data_access_2_earthdata.ipynb
  book/tutorials/data_access/img/data_provider_cheat_sheet.png
Labels: preview

#99 Videos Day 1
  book/schedule.yaml
  {{ cookiecutter.repo_directory }}/index.html
Labels: preview

#101 add link to the project spreadsheet
  book/_config.yml
  book/intro.md
Labels: preview

#102 Preliminary - EarthData - Update instructions for netrc
  book/preliminary/earthdata.md
Labels: preview

#98 Finalized versions of Data Integration Tutorials
  book/tutorials/DataIntegration/dataintegration-1.ipynb
  book/tutorials/DataIntegration/dataintegration-2.ipynb
  book/tutorials/DataIntegration/processed_ATL06_20190420093051_03380303_005_01.h5
Labels: preview

#103 Starting geospatial transforms following run through
  book/tutorials/geospatial/geospatial-advanced.ipynb
  book/tutorials/geospatial/geospatial-intro.ipynb
  book/tutorials/geospatial/utilities.py
Labels: preview

#104 add files from live tutorial
  book/tutorials/ObjectOriented/OOP_slides.pdf
  book/tutorials/ObjectOriented/OOP_tutorial_live.ipynb
Labels: preview

#89 add initial data applications with SR
  .github/actions/buildresources/action.yaml
  book/_toc.yml
  book/tutorials/DataIntegration/data-applications.ipynb
Labels: preview

#105 Update jupyterbook cache
  .github/actions/buildresources/action.yaml
Labels: preview

#106 Tutorial index - Fix table with recordings.
  book/tutorials/index.md
Labels: preview

#109 update projects table with 2022 projects
  book/projects/list_of_projects.md
Labels: preview

#110 Book TOC - Promote the list of projects higher up.
  book/_toc.yml
Labels: preview

#113 Schedule Day3
  book/schedule.yaml
  book/tutorials/index.md
Labels: preview

#114 Schedule - Add videos for day 4
  book/schedule.yaml
  book/tutorials/index.md
Labels: preview

#116 Landing page - Select the tab with the current day upon load.
  {{ cookiecutter.repo_directory }}/assets/js/main.js
  {{ cookiecutter.repo_directory }}/index.html
Labels: preview

#115 Add --warningiserror flag to jupyter book build command
  book/projects/list_of_projects.md
  book/tutorials/DataIntegration/dataintegration-1.ipynb
  book/tutorials/DataProducts/DataProducts.ipynb
  book/tutorials/index.md
  scripts/build_resources.sh
Labels: preview
